name: dart_awesome_lint_workspace

packages:
  - packages/**

scripts:
  analyze:
    exec: dart analyze .

  lint:dart:
    exec: dart run custom_lint
    packageFilters:
      dependsOn: [ "custom_lint"]
      noDependsOn: "flutter"

  lint:flutter:
    exec: flutter pub run custom_lint
    packageFilters:
      dependsOn: [ "custom_lint", "flutter" ]
