name: dart_awesome_lint
description: "A Dart package that provides custom lint rules for the Dart language."
version: 0.0.2
repository: https://github.com/akaboshinit/dart_awesome_lint

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  analyzer: ^7.0.0
  analyzer_plugin: ^0.12.0
  custom_lint_builder: 0.7.1

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^7.0.0
